<a href="https://colab.research.google.com/github/passionatedimpact/Python-Fundamental/blob/main/Python_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PYTHON GENERAL FUNDAMENTALS**

This is a general details guide to python fundamentals. NOTE: in-built python function will be written with bold italic for easy identification. This material is generated by KUFRE FRANK +234 07082359258 impactfulshare@gmail.com

(***PLEASE NOTE YOU MEET SOME ERRORS IN THIS RESOURCES MATERIAL BECAUSE THIS IS STILL DEVELOPING***)

In [ ]:
 HINT: Every concept has trends. To do well on any concept find trends that belong to the concept or within the niche.

** HINT:**
1. Every concept has trends, do well find trends that belong in any concept
2. Every in-built function starts with a small letter and must end with a () with codes within it.
3. Always use a comma (,) to seperate a string from a numerical value
4.
5.
6.
7.
8.
9. Indexing with python starts with zero (0)
10.

## Easy Class:
**Repition:** Don't be in haste to ccomprehesively complete each concept. For every concept repeat it with personal example.

1. **Grouping and ordeering concepts in  chapters**


1. #: for Textbook name
2. ##: for concept
3. ###:  for Topic
4. ####: for Subtopic

1. ## **COMMENT**

1.  ***comment()*** : comments are lines in the code that are ignored by the interpreter, allowing programmers to leave notes or explanations within their code. There are a few different ways to write comments in Python
**TYPES**
*   single-line comment
*   multiple-line comment
*   block comment (docstring)
*   Inline comment:

a. **Single-line Comments**: Starts with a # symbol. Everything after # on that line is considered a comment by python. Also note, The comment after the print statement is like a side note **Example** below

In [ ]:
# This is an example of a single line comment
print("Hello, hope you are excited to learn this course!")  # This line prints the greeting and the expressional hope. Check below for the Output

Hello, hope you are excited to learn this course!

b. **Inline Comments**: Places a comment on the same line as the code, after a space. ***Example*** below

In [ ]:
# prompt: give an example of inline comment

print("Hello, Kufre!")  # This is an inline comment explaining the code.

Hello, Kufre!

c. **Multiple single-line comments:** done by placing a # at the beginning of each line of a write-up. Example below.**bold text**

In [ ]:
# prompt: example of multiple line comments
# This is a multiple line comment
# This is an example of multiple lines of comments
# The interpreter will skip it and not run it
# This will be useful when your write up is too long
a = 10
b = 20
c = a + b
print('The result is', c)
print("Hello, hope you are excited to learn this course!")

The result is 30
Hello, hope you are excited to learn this course!

d. **Docstring or Multi-line using proper tripple single/double qoutes:** Use triple quotes " " " for larger explanations before and after while the extensive detail comments is within. **Analogy:**
Think of this like writing a note at the beginning of a project explaining everything it does, like an introduction in a book. ***Example*** below.

In [ ]:
"""
Block comment (docstrings) written
explains what the code does, but it won’t affect the program’s execution.
Often use when the explanatory comments is a long one.
"""
print("Hello! note the uniqueness of each comment")

Hello! note the uniqueness of each comment

***Try as much as possible to use different comment method so you get use to
them.***

##2. **VARIABLES**

VAriables (summary)
1. **Integer (int)**: Holds whole numbers: , 80, 102, 100534, etc.
2. **Float (float)**: A number with a decimal point. It can represent fractions: 2.5, 0.56, 95.05
3. **String (str)**: Store a sequence of characters (text): Name, address,
4. **Boolean (bool):** Stores anytwo probability variale which are opposite to each other: True or False, God or Satan.
5. **List**: Holds multiple items in an *ordered sequence*: ["apple", "banana", "mango"],
6. **Tuple:** Like a list, but unchangeable.
7. **Dictionary (dict)**: Store an ordered collection of items (cannot be changed after creation)
8. **Set:** Definition: A collection of unique items that are unordered and unindexed.

*NOTE: There more to this. Click on the link to access more. click on the link*
https://docs.google.com/spreadsheets/d/1mO_CJE5EMGWAJ_gKwUFewp2VzcwTiqQXVpCxUlsF4ss/edit?gid=918770401#gid=918770401

**DATA STRUCTURES**
Data structures in Python are special types of variablesL List, Tuple, Dictionary and Set.

**List**
---
**Analogy:**
Think of a list like a grocery shopping list. Each item on the list is in a specific order, and you can add, remove, or modify items as you shop. For example, if you had "bananas" but decide to get "oranges" instead, you can easily change your list.

**Defination:**
A list is a collection of ordered, mutable items. Lists are widely used to store a collection of related data elements in a sequence, and they can contain elements of different types, such as numbers, strings, and even other lists.
NOTE: A list can contain any of the four basic data type also a list can also contains a subset seperated by a comma.

Key Features:
*   **Ordered:** The elements in a list have a defined order, and you can access them by their index.
*   **Mutable:** You can change, add, or remove elements after the list is created.
*   **Diverse Data Types:** Lists can store multiple data types, such as integers, strings, or other lists.
*   Syntax: it uses square bracket [  ]
*   Unique: The only variable data structure that uses  a square bracket []
*   **First index** is always consider 0. Therefor if 'L' is consider as the last ordered position, the total COUNT will be gotten by 'L - 1'

**Use Case:**
Lists are great for situations where you need a collection of items that you can modify later. For example, a list of shopping items, tasks in a to-do list, or data points in a chart.

![Variable List Data Structure Python JPEG.JPG]()


---

### **1. create a list**
source: datacamp/intro-to-python-for-data-science

In [ ]:
# list example with strings and Integers
family_weight = ["father", 87.5, "Mother", 90.2, "1st_child", 52.6, "2nd_child", 47.23, "3rd_child", 38, "4rd_child" , 30 , "5th_child", 20]
print(family_weight)

['father', 87.5, 'Mother', 90.2, '1st_child', 52.6, '2nd_child', 47.23, '3rd_child', 38, '4rd_child', 30, '5th_child', 20]

In [ ]:
# list example 2: with strings and Integers with distinctive seperation
family_weight_2 = [["father", 87.5], ["Mother", 90.2], ["1st_child", 52.6], ["2nd_child", 47.23], ["3rd_child", 38], ["4rd_child" , 30] , ["5th_child", 20]]
print(family_weight_2)

[['father', 87.5], ['Mother', 90.2], ['1st_child', 52.6], ['2nd_child', 47.23], ['3rd_child', 38], ['4rd_child', 30], ['5th_child', 20]]

In [ ]:
# # list with lists as a subset
# list within a list
family_weight_3 = [[ "father", 87.5],
 ["Mother", 90.2],
  ["1st_child", 52.6],
   ["2nd_child", 47.23],
    ["3rd_child", 38],
     ["4rd_child" , 30],
      ["5th_child", 20]]
print(family_weight_3)

[['father', 87.5], ['Mother', 90.2], ['1st_child', 52.6], ['2nd_child', 47.23], ['3rd_child', 38], ['4rd_child', 30], ['5th_child', 20]]

In [ ]:
# list: string_value
d = 'Delta'
e = 'Epsilon'
Greek_Alphabet = ["4rd", "5th", d, e, "respectively"]
print(Greek_Alphabet)

['4rd', '5th', 'Delta', 'Epsilon', 'respectively']

In [ ]:
# create list of names and indexing
names = ["Tunde", "Bola", "Sade", "Kola", "Ada", "Emeka"]
print(names [0])
print (names [1])
print (names [2])
print (names [3])
print (names [4])
print (names [5])

Tunde
Bola
Sade
Kola
Ada
Emeka

### **2. Accessing an Item on a list (also applicable for Turple, Strings)**
Any Particular item can be access on a list through the index number using either **Positive Indexing** or **Negative Indexing.**

**Positive Index:** Starts from *Left* to *Right* with a *starting index* 0f *0*
**Nagative Index:** Starts from *Right* to *left* with a *starting index* 0f *-1* considering the last item as the first and so forth.

**Example:**
Position from front (positive index): [0,  1,      2,   3,   4,    5]

Students in line:                       [Tunde, Bola, Sade, Kola, Ada, Emeka]

Position from back (negative index): [-6, -5, 	 -4,   -3,  -2,   -1]


DETAILS: Please click on the link to read more.

In [ ]:
# Acessing an Item on a list with previous created list is not possible. It must be define within the same cell.
family_weight_2 = ['7kg', '2kg', '3kg', '9kg', '12kg']
print(family_weight_2[3]) # *Positive indexting*
print(family_weight_2[-4]) # *Negative indexting*

9kg
2kg

#### **Positive indexing**

### **List: *Appending* /How to Add an item to already existing List**
Methods:
1. Single element? → append()
2. Multiple elements? → extend() or +=
3. Insert at a position? → insert()
4. Need a new list? → + pop ()

#### Method 1: syntax: **Variabl_Name*.append()***

In [ ]:
# METHOD 1a (Numeric): Direct Method
my_list_1 = [1, 2, 3]  # Existing list already defined
my_list_1.append(4)  # Appending an integer value adds it to the list
print(my_list_1)  # Output: [1, 2, 3, 4]

[1, 2, 3, 4]

In [ ]:
# METHOD 1b (Numeric): Indirect Method
my_list_2 = [1, 2, 3]  # Existing list
value_to_append = 4  # Integer to append
my_list_2.append(value_to_append)
print(my_list_2)  # Output: [1, 2, 3, 4]

[1, 2, 3, 4]

In [ ]:
# METHOD 2a (Strings): Direct Method
my_list_3 = ["Lia", "Stephen", "Daniel"]  # Existing list of strings
my_list_3.append("John")  # Appending a string value to the list
print(my_list_3)  # Output: ['Lia', 'Stephen', 'Daniel', 'John']

['Lia', 'Stephen', 'Daniel', 'John']

2

#### **extend**

#### **Aggregation and Grouping**

### **Tuple**

In [ ]:
### develop note on the abve topic  TUPLE

### **Dictionary**

In [ ]:
### develop note on the concept of  DICTIONARY

### **Set**

In [ ]:
### develop a note on the concept of SET

Variable Summary


![Variable Summary.JPG]()

**Example: (extensive)**

In [ ]:
### Below are extensive exalples of all kind of Variables.

In [ ]:
# VARIABLES: This are types of variables in programming
int_Var1 = 80
int_Var2 = 10

float_Var = 0.56
float_Var2 = 10.5

str_Var1 = "Kufre"
str_Var2 = "Frank"

bool_Var1 = True
bool_Var2 = False

list_Var1 = ["apple", "banana", "mango"]
list_Var2 = [1, 2, 3, 4, 5]
list_Var3 = [True, False, False]
list_Var4 = ["abc", 34, True, 40, "male"]

tuple_Var1 = ("apple", "banana", "mango")
tuple_Var2 = (1, 2, 3, 4, 5)
tuple_Var3 = (True, False, False)
tuple_Var4 = ("abc", 34, True, 40, "male")
tuple_Var5 = ("apple", "banana", "mango", 1, 2, 3, 4, 5, True, False, False)

dict_Var1 = {"name": "Kufre", "age": 25}
dict_Var2 = {"name": "Kufre", "age": 25, "city": "Lagos"}
dict_Var3 = {"name": "Kufre", "age": 25, "city": "Lagos", "country": "Nigeria"}
dict_Var4 = {"name": "Kufre", "age": 25, "city": "Lagos", "country": "Nigeria", "name": "Frank"}
dict_Var5 = {"name": "Kufre", "age": 25, "city": "Lagos", "country": "Nigeria", "name": "Frank", "name": "Frank"}

set_Var1 = {"apple", "banana", "mango"}
set_Var2 = {1, 2, 3, 4, 5}
set_Var3 = {True, False, False}
set_Var4 = {"abc", 34, True, 40, "male"}
set_Var5 = {"apple", "banana", "mango", 1, 2, 3, 4, 5, True, False, False}
set_Var6 = {"apple", "banana", "mango", 1, 2, 3, 4, 5, True, False, False, "apple", "banana", "mango", 1, 2, 3, 4, 5, True, False, False}

Summary:

**Assignment:** Explain the following type of variables (data structure) explicitly with 10 examples each in your own words.



---


*Get set for a new concept: TYPE*


---



---

##3. **TYPE**

### type () : in-built function that declare the type of variable one is working with.

Use the **'type'** in-built function to declare the type of variables in the examples above.

In [ ]:
int_Var1 = 80
type(int_Var1)

int

In [ ]:
k = "Anita"
type(k)

str

In [ ]:
float_Var = 0.56
type (float_Var)

float

In [ ]:
str_Var = "Kufre"
type (str_Var)

str

In [ ]:
bool_Var1 = True
type (bool_Var1)

bool

In [ ]:
list_Var4 = ["abc", 34, True, 40, "male"] # note the type of bracket
type (list_Var4)

list

In [ ]:
tuple_Var5 = ("apple", "banana", "mango", 1, 2, 3, 4, 5, True, False, False) # note the type of bracket
type (tuple_Var5)

tuple

In [ ]:
dict_Var5 = {"name": "Kufre", "age": 25, "city": "Lagos", "country": "Nigeria", "name": "Frank", "name": "Frank"} # note the type of bracket
type (dict_Var5)

dict

In [ ]:
set_Var6 = {"apple", "banana", "mango", 1, 2, 3, 4, 5, True, False, False, "apple", "banana", "mango", 1, 2, 3, 4, 5, True, False, False} # note the type of bracket
type (set_Var6)

set

Slicing **Strings**










---




*Get set for a new concept: PRINT*

---


---

##4. **PRINT()**
Different ways to use print in-built function:
1.
2.
3.
4.
5.
6.
7.
8.
9.
10.

In [ ]:
# Direct Method
# Addition
print(4+5)

# Subtraction
print(5-5)

# Multiplication
print(3*5)

# Division
print(10/2)

9
0
15
5.0

## **INPUT FUNCTION**










---




*Get set for a new concept: CONCATENATION*

---


---










---




*Get set for a new concept: ARITHMETIC OPERATORS*

---


---

In [ ]:
#

## **BASIC OPERATIONS  ON VARIABLES**

1.   Concatenation
2.   Slicing
3.   Repitition
4.   Trimming
5.   Srting Transformation

### **Concatenation**

### **Slicing**
It allows user to access parts of sequences like lists, strings, and tuples. This like extrcting a part of an audio, a video, of a written document.

**start**: The index (zero) at which the slice starts (*inclusive*).
**stop**: The index at which the slice ends (*exclusive*).
**step**: The interval or step size between elements in the slice (alternative).

**Syntax** = sequence[start : end :step] It must have a colon in it's syntax.

Indexting start 0 gives the first element While -1 give the first element from the back

**Confusing Behavior:** If the slicing bounds (start, stop) do not match the direction of the step, it results in an empty slice.

**bold text**# New Section

In [ ]:
## Slicing: Extracting a Range of Elements
My_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,20]
print(My_list[0:15]) # starts from the 1st item (0) and gives the first 15 output up to (14)
print(My_list[0:17])
print(My_list[2:19:3]) # Starts with the 3rd item to the 18th and output at every interval (step) of 3
print(My_list[4:12:])
print(My_list[9:9]) # empty output
print(My_list[8:5:]) # empty output because the end is not possible
print(My_list[12:19:3])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
[2, 5, 8, 11, 14, 17]
[4, 5, 6, 7, 8, 9, 10, 11]
[]
[]
[12, 15, 18]

#### **Omitting: Start or Stop**
Omit the start index, slicing starts from the beginning of the sequence.
Omit the stop index, slicing goes to the end of the sequence.

In [ ]:
# Omitting Start
print(My_list[:5]) # omit start, output from the end to the start
print(My_list[:7:2]) # Omit Start, output from the 7th term but only at every interval of two.
print(My_list[::]) # start from the beginning (the entire life) to the end without any interval
print(My_list[::2]) # start from beginning to the end but only output at every two interval

[0, 1, 2, 3, 4]
[0, 2, 4, 6]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 2, 4, 6, 8, 10]

In [ ]:
# Omitting end
print(My_list[3:])
print(My_list[3::2])
print(My_list[3::])
print(My_list[3::2])

[3, 4, 5, 6, 7, 8, 9, 10]
[3, 5, 7, 9]
[3, 4, 5, 6, 7, 8, 9, 10]
[3, 5, 7, 9]

#### **Negative Index Slicing**
Negative slicing in Python allows you to access elements from the end of a list or string. It’s like counting backwards.

1/3 **A negative start index:**
Specifies the starting position from the end of the sequence.
For example, my_list[-2:] starts from the second-to-last element and goes to the end. *It count backwards from the end of the list.*

2/3 **Negative stop Index:**
The stop index indicates where the slicing ends. If it’s negative, it specifies the ending position (exclusive) from the end of the sequence. it counts backward from the end of the sequence. The slice ends before the specified index.
*For example, my_list[:-2] goes from the beginning to the second-to-last element (excluding it).*

3/3 **A negative step Index:**
 reverses the direction of the slice from right to left.

In [ ]:
# START negative index (NOTE THE DIFFERENCE BETWEEN SLICING AND COUNT)
print(My_list[:]) # NO NOTHING but ouput everything
print(My_list[-8:]) # SLICING: because of the colon (:) symbol. Count forward from the 8th term from the back.
print(My_list[-8]) # COUNT: count does not have a colon symbol
print(My_list[-5::]) # Count forward from the 5th term from the back.
print(My_list[-17]) # COUNT

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[13, 14, 15, 16, 17, 18, 19, 20]
13
[16, 17, 18, 19, 20]
4

In [ ]:
# STOP Negative Index
print(My_list[:3]) # NOT negative Index: output from eginning to 3rd element where it ends.
print(My_list[:-8]) # Output forward from beginning and ends just before the 8th term counting from the last.
print(My_list[-8]) # COUNT: output the 8th element from the back

[0, 1, 2]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
13

In [ ]:
# STEP Negative Index Slicing: reversese the order from back (Right) to farward (Left)
print(My_list[::-8]) # At interval of 8 reversing the order from back (right) to the beginning (wrong).

[20, 12, 4]

#### **Combined Indexes**

In [ ]:
## Negative start and stop with Positive step:
print(My_list[-5:])
print(My_list[-12:-5]) # start fro the 12th element fron the back (9) and stop at 5th element from the back

[16, 17, 18, 19, 20]
[9, 10, 11, 12, 13, 14, 15]

In [ ]:
# Negative start, stop and step:
print(My_list[-5:-13:-2])
print(My_list[-4:-17:-3])

[16, 14, 12, 10]
[17, 14, 11, 8, 5]

### **Repitition**

Repititon allows a string or any element to repeat itself several times.
Examples #5

In [ ]:
#Example1: Using the * Operator (for both strings and lists of numbers)
Greetings = "hello" * 3
Num = [1, 2, 3] * 3
Combine = ["hello", "world"] * 2
String_Num = ["hello", "Set to go ", 1, 2, 3] * 2
print(Greetings)
print(Num)
print(Combine)
print(String_Num)

hellohellohello
[1, 2, 3, 1, 2, 3, 1, 2, 3]
['hello', 'world', 'hello', 'world']
['hello', 'Set to go ', 1, 2, 3, 'hello', 'Set to go ', 1, 2, 3]

In [ ]:
#Example 2:  Using List Comprehension (for Numbers)
result_num = [5 for _ in range(4)]
Strgn =  [ "Jesus is Lord" for _ in range(6)]
print(result_num)
print(Strgn)

[5, 5, 5, 5]
['Jesus is Lord', 'Jesus is Lord', 'Jesus is Lord', 'Jesus is Lord', 'Jesus is Lord', 'Jesus is Lord']

In [ ]:
# Example 3b: Using join() for Strings without Separator
Jesus_lordship = (["Jesus Is Lord"] * 3) # Repeat a string with spaces as separator
print(Jesus_lordship)

Jesus Is Lord Jesus Is Lord Jesus Is Lord

In [ ]:
# Exammple 3: Using join() for Strings with Separator
relt_str = " ".join(Jesus_lordship)
print(relt_str)

Jesus Is Lord Jesus Is Lord Jesus Is Lord

### String Transformations
String transformations manipulate or change the structure of a string. Some common transformations include changing cases, replacing characters, splitting, and formatting.

No of Examples: 5
https://chatgpt.com/g/g-2DQzU5UZl-code-copilot/c/672d56d5-b618-8005-9fb6-e56818430c87

In [ ]:
# Example 1: Changing Case
text = "Jesusn is Lord"
print(text.upper())    # HELLO WORLD
print(text.lower())    # hello world
print(text.title())    # Hello World

JESUSN IS LORD
jesusn is lord
Jesusn Is Lord

In [ ]:
#  Example 2: Replacing Substrings.
#  https://chatgpt.com/g/g-2DQzU5UZl-code-copilot/c/672d56d5-b618-8005-9fb6-e56818430c87
transformed = "Jesus is Lord"
transformed = text.replace("Lord", "Reigning")
print(transformed)

Jesusn is Reigning

### Trimming

Python provides straightforward methods for trimming whitespace, specific characters, or both.

a. Using strip(), lstrip(), and rstrip()
strip(): Removes leading and trailing whitespace by default but can also remove specified characters.
lstrip(): Removes leading whitespace or specified characters.
rstrip(): Removes trailing whitespace or specified characters.
Example:
https://chatgpt.com/c/672d70de-c848-8005-96c2-218df85b75d0

### **List Modification (Manipulation)**  
**Analogies:**
1.   Think of a **list** in Python like a *school backpack 💰*. You can put in books, pens, snacks—anything. Each time you add something, you’re using **.append()**
2. The **append()** method in Python is like adding ingredients to a *pot* of soup 🍲—you keep tossing items into a **list** (the pot) one by one.

**NOTE:**

**TYPES:**
1. **1. append():**
Adds a *single *elememt to the *end* of a list
2. **2. extend():**
Adds a *multiple* elememts to the *end* of a list (adds more list, turple, string, Dictionaries, set)
3. **3. insert():**
Adds a single elelemt at a specified position in a list.
4. **4. pop():**
Removes and returns an elements from a list at a specified index (or the last element if no index is specified)

**NOTE:** pop() is the only modification that subtract from list while the rest add to a list

**Further Studies:**
1. *List manipulation and Iteration*
2.   List item
3.   List item

1. **append()** : Adds a *single* elememt to the *end* of a *list*.

In [ ]:
# 🎒 Example 1a: Adding items to an empty list using.
# Analogy: School Bag
backpack = []
backpack.append("Eraser")
backpack.append("Pencil")
backpack.append("Snacks")

print(backpack)
# Output: ['Eraser', 'Pencil', 'Snacks']

['Eraser', 'Pencil', 'Snacks']

In [ ]:
# 🔬 Example 1b : Adding items to an empty list using .append() with strings
# Recording temperature readings in an experiment
temperatures = []
temperatures.append(25.3)
temperatures.append(26.1)
temperatures.append(24.9)

print("Recorded Temperatures:", temperatures)
# Output: Recorded Temperatures: [25.3, 26.1, 24.9]

Recorded Temperatures: [25.3, 26.1, 24.9]

In [ ]:
# Example 2a: append() to non-empty list
# Analogy: Adding to a Food List
foods = ["Rice", "Beans"]
print("Before:", foods)

foods.append("Yam")  # Adds "Yam" to the list
print("After:", foods)

Before: ['Rice', 'Beans']
After: ['Rice', 'Beans', 'Yam']

In [ ]:
# EXAMPLE 2b: NESTED LISTS adding a list to  lIST
# ANALOGY: for grades in school

class_grades = []
math_scores = [85, 90, 78]
science_scores = [88, 92, 84]

class_grades.append(math_scores)
class_grades.append(science_scores)

print("All Grades:", class_grades)

All Grades: [[85, 90, 78], [88, 92, 84]]

In [ ]:
#Example 3a: Appending Numbers to EMPTY list
#Analogy: Math Application - iteration
numbers = []  # Empty list
for num in range(1, 6):
    numbers.append(num)  # Adds 1, 2, 3, 4, 5

print("Numbers:", numbers)

In [ ]:
#Example 3b: Appending Numbers to Non-Empty list
#Analogy: Math Application - iteration
numbers = [9,8,7,]  # Non-Empty list
for num in range(0, 5):
    numbers.append(num)  # Adds 1, 2, 3, 4, 5

print("Numbers:", numbers)

Numbers: [9, 8, 7, 0, 1, 2, 3, 4]

In [ ]:
#Example 3c: Appending Numbers to Non-Empty list + slicing
#Analogy: Math Application - iteration
numbers = [9,8,7,]  # Non-Empty list + slicing
for num in range(0, 20, 5):
    numbers.append(num)  # Adds 1, 2, 3, 4, 5

print("Numbers:", numbers)

Numbers: [9, 8, 7, 0, 5, 10, 15]

In [ ]:
#Example 3d: Appending Numbers to Non-Empty list
#Analogy: Math Application - iteration
numbers = ['A', 'B', 'C',]  # Empty list
for num in range(1, 6):
    numbers.append(num)  # Adds 1, 2, 3, 4, 5

print("Numbers:", numbers)

Numbers: ['A', 'B', 'C', 1, 2, 3, 4, 5]

In [ ]:
# Example 4a: Further study
# Analogy: ===== INTERACTIVE STUDENT LIST =====

students = []
while True:
    name = input("Enter student name (or 'stop' to end): ")
    if name.lower() == "stop":
        break
    students.append(name)

print("\nClass List:", students)

Enter student name (or 'stop' to end): Jamine
Enter student name (or 'stop' to end): Jeremiah
Enter student name (or 'stop' to end): Joseph
Enter student name (or 'stop' to end): Jacob
Enter student name (or 'stop' to end): Stop

Class List: ['Jamine', 'Jeremiah', 'Joseph', 'Jacob']

In [ ]:
# Example 4b: Further study
# Analogy: SHOPPING LIST BUILDER

shopping_list = []

while True:
    item = input("Add item to shopping list (or 'done' to finish): ")
    if item.lower() == 'done':
        break
    shopping_list.append(item)

print("\nYour Shopping List:")
for item in shopping_list:
    print(f"- {item}")

Add item to shopping list (or 'done' to finish): Egg
Add item to shopping list (or 'done' to finish): Biscuit
Add item to shopping list (or 'done' to finish): Sugar
Add item to shopping list (or 'done' to finish): Milk
Add item to shopping list (or 'done' to finish): Done

Your Shopping List:
- Egg
- Biscuit
- Sugar
- Milk



1.   List item
2.   List item


---

*Get set for a new concept: Comparison OPERATORS*

---
---

## **Operator**

**Comparison Operators:**
1. Equal (==)
2. Not Equal (!=)
3. Greater Than (>)
4. Less Than (<)

**Logical Operators:**
1. AND (and)
2. OR (or)
3. NOT (not)

### **Expression**

An Expression is a combination of variables, operators and values that produce a result.
*  a. Arithmetic Expression: Perform Mathematical operations (3+5*2)
*  b. String Expressions: Concentration or manipulate string ("Hello," + "World!")
*  c. Boolean Expressions: Evaluate True or False (5 > 3)

In [ ]:
# Arithmetic Expression
a = (4 + 6) % 2 # I am calculating using modulus (Which focuses on the remainder when dividing)
print('a. You are correct it is', a)

a. You are correct it is 0

**Modulus (%) a.k.a Remainder**

*Q?: What is the difference between an Expression and an Equation?*
*Ans:*